import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { API_BASE } from '../../api';

@Component({
  standalone: true,
  imports: [CommonModule],
  template: `
  <section class="panel">
    <p class="eyebrow">Monthly Dialog billing</p>
    <h2>Upload monthly Dialog invoice</h2>
    <p>Upload the original .xls/.xlsx generated by Dialog. The ERP builds the monthly output automatically.</p>

    <input type="file" accept=".xls,.xlsx" (change)="choose($event)">
    <button (click)="upload()" [disabled]="!file || uploading">{{uploading ? 'Uploading…' : 'Upload and build output'}}</button>
    <p *ngIf="error" class="error">{{error}}</p>
    <p *ngIf="importResult?.idempotent">This monthly invoice was already imported. Existing output is shown; no duplicate rows were created.</p>

    <ng-container *ngIf="report">
      <hr>
      <p class="eyebrow">Monthly output</p>
      <h2>{{report.invoice?.bill_period || report.batch?.period_end || 'Billing cycle'}}</h2>
      <div class="cards">
        <article><b>{{report.invoice?.invoice_number || '—'}}</b><span>Invoice number</span></article>
        <article><b>{{report.invoice?.corporate_code || report.batch?.contract_no || '—'}}</b><span>Corporate code</span></article>
        <article><b>{{report.totals?.lines || 0}}</b><span>Billing lines</span></article>
        <article><b>{{report.totals?.charges_for_bill_period | number:'1.2-2'}}</b><span>Charges for bill period (LKR)</span></article>
        <article><b>{{report.totals?.total_amount_payable | number:'1.2-2'}}</b><span>Dialog total outstanding (LKR)</span></article>
        <article><b>{{report.totals?.unmatched || 0}}</b><span>Unmatched numbers</span></article>
      </div>

      <div style="margin:1rem 0; display:flex; gap:.75rem; flex-wrap:wrap;">
        <button (click)="downloadWorkbook()" [disabled]="downloading">{{downloading ? 'Building Excel…' : 'Download Updated Excel'}}</button>
      </div>

      <p><b>Recovery basis:</b> current month's Charges for Bill Period. Previous outstanding balances are preserved in the workbook but are not added to the monthly recovery basis.</p>

      <div *ngIf="report.issues?.length"><h3>Quality checks</h3><p *ngFor="let q of report.issues">{{q.severity}} · {{q.issue_type}} · {{q.count}}</p></div>

      <div style="overflow:auto; max-height:60vh; margin-top:1rem;">
        <table style="width:100%; border-collapse:collapse; min-width:1200px;">
          <thead><tr><th>Mobile No</th><th>Previous Due</th><th>Payment</th><th>Usage Charges</th><th>IDD</th><th>Roaming</th><th>VAS</th><th>Gov. Taxes</th><th>VAT</th><th>Charges for Period</th><th>Dialog Total Payable</th><th>Match</th></tr></thead>
          <tbody><tr *ngFor="let r of report.lines"><td>{{r.mobile_display}}</td><td>{{r.previous_due_amount}}</td><td>{{r.payment}}</td><td>{{r.total_usage_charges}}</td><td>{{r.idd}}</td><td>{{r.roaming}}</td><td>{{r.vas}}</td><td>{{r.government_taxes}}</td><td>{{r.vat}}</td><td>{{r.charges_for_bill_period | number:'1.2-2'}}</td><td>{{r.total_amount_payable | number:'1.2-2'}}</td><td>{{r.match_status}}</td></tr></tbody>
        </table>
      </div>
    </ng-container>
  </section>`
})
export class ImportsComponent {
  file?: File; uploading=false; downloading=false; error=''; importResult:any; report:any; billingBatchId?:number;
  constructor(private http:HttpClient){}
  choose(event:Event){const input=event.target as HTMLInputElement;this.file=input.files?.[0]||undefined;this.error='';this.importResult=null;this.report=null;this.billingBatchId=undefined;}
  upload(){if(!this.file)return;this.uploading=true;this.error='';const form=new FormData();form.append('file',this.file);this.http.post<any>(`${API_BASE}/imports/workbook`,form).subscribe({next:result=>{this.importResult=result;this.billingBatchId=result?.billingBatchId;if(!this.billingBatchId){this.uploading=false;this.error='Import completed but no billing batch was returned.';return;}this.loadReport(this.billingBatchId);},error:e=>{this.uploading=false;this.error=e?.error?.message||'Monthly invoice upload failed.';}});}
  private loadReport(id:number){this.http.get<any>(`${API_BASE}/reports/billing/${id}`).subscribe({next:r=>{this.report=r;this.uploading=false;},error:e=>{this.uploading=false;this.error=e?.error?.message||'Invoice imported, but output could not be loaded.';}});}
  downloadWorkbook(){if(!this.billingBatchId)return;this.downloading=true;this.error='';this.http.get(`${API_BASE}/reports/billing/${this.billingBatchId}/workbook`,{responseType:'blob',observe:'response'}).subscribe({next:res=>{const blob=res.body;if(!blob){this.downloading=false;this.error='Excel output was empty.';return;}const cd=res.headers.get('content-disposition')||'';const m=/filename="?([^";]+)"?/i.exec(cd);const name=m?.[1]||'Dialog_Recovery.xlsx';const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);this.downloading=false;},error:e=>{this.downloading=false;this.error=e?.error?.message||'Unable to build the updated Excel workbook.';}});}
}
