import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { API_BASE } from '../../api';

@Component({
  standalone: true,
  imports: [CommonModule],
  template: `
  <section class="panel">
    <p class="eyebrow">Monthly Dialog billing</p>
    <h2>Upload monthly Dialog invoice</h2>
    <p>
      Upload the original monthly .xls/.xlsx file generated by Dialog.
      Invoice number, corporate code and billing period are read automatically from the workbook.
    </p>

    <input type="file" accept=".xls,.xlsx" (change)="choose($event)">
    <button (click)="upload()" [disabled]="!file || uploading">
      {{uploading ? 'Uploading…' : 'Upload and build output'}}
    </button>

    <p *ngIf="error" class="error">{{error}}</p>
    <p *ngIf="importResult?.idempotent">
      This monthly invoice was already imported. Existing output is shown below; no duplicate rows were created.
    </p>

    <ng-container *ngIf="report">
      <hr>
      <p class="eyebrow">Monthly output</p>
      <h2>{{report.invoice?.bill_period || report.batch?.period_end || 'Billing cycle'}}</h2>

      <div class="cards">
        <article><b>{{report.invoice?.invoice_number || '—'}}</b><span>Invoice number</span></article>
        <article><b>{{report.invoice?.corporate_code || report.batch?.contract_no || '—'}}</b><span>Corporate code</span></article>
        <article><b>{{report.totals?.lines || 0}}</b><span>Billing lines</span></article>
        <article><b>{{report.totals?.charges_for_bill_period | number:'1.2-2'}}</b><span>Charges for bill period (LKR)</span></article>
        <article><b>{{report.totals?.total_amount_payable | number:'1.2-2'}}</b><span>Total amount payable (LKR)</span></article>
        <article><b>{{report.totals?.unmatched || 0}}</b><span>Unmatched numbers</span></article>
      </div>

      <div *ngIf="report.issues?.length">
        <h3>Quality checks</h3>
        <p *ngFor="let q of report.issues">
          {{q.severity}} · {{q.issue_type}} · {{q.count}}
        </p>
      </div>

      <div style="overflow:auto; max-height:60vh; margin-top:1rem;">
        <table style="width:100%; border-collapse:collapse; min-width:1200px;">
          <thead>
            <tr>
              <th>Mobile No</th>
              <th>Previous Due</th>
              <th>Payment</th>
              <th>Usage Charges</th>
              <th>IDD</th>
              <th>Roaming</th>
              <th>VAS</th>
              <th>Gov. Taxes</th>
              <th>VAT</th>
              <th>Charges for Period</th>
              <th>Total Payable</th>
              <th>Match</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let r of report.lines">
              <td>{{r.mobile_display}}</td>
              <td>{{r.previous_due_amount}}</td>
              <td>{{r.payment}}</td>
              <td>{{r.total_usage_charges}}</td>
              <td>{{r.idd}}</td>
              <td>{{r.roaming}}</td>
              <td>{{r.vas}}</td>
              <td>{{r.government_taxes}}</td>
              <td>{{r.vat}}</td>
              <td>{{r.charges_for_bill_period | number:'1.2-2'}}</td>
              <td>{{r.total_amount_payable | number:'1.2-2'}}</td>
              <td>{{r.match_status}}</td>
            </tr>
          </tbody>
        </table>
      </div>

      <p *ngIf="report.totals?.unmatched">
        Recovery generation should remain on hold until the corporate connection master is loaded and these numbers are reconciled.
      </p>
    </ng-container>
  </section>`
})
export class ImportsComponent {
  file?: File;
  uploading = false;
  error = '';
  importResult: any;
  report: any;

  constructor(private http: HttpClient) {}

  choose(event: Event) {
    const input = event.target as HTMLInputElement;
    this.file = input.files?.[0] || undefined;
    this.error = '';
    this.importResult = null;
    this.report = null;
  }

  upload() {
    if (!this.file) return;
    this.uploading = true;
    this.error = '';
    const form = new FormData();
    form.append('file', this.file);

    this.http.post<any>(`${API_BASE}/imports/workbook`, form).subscribe({
      next: result => {
        this.importResult = result;
        const billingBatchId = result?.billingBatchId;
        if (!billingBatchId) {
          this.uploading = false;
          this.error = 'Import completed but no billing batch was returned.';
          return;
        }
        this.loadReport(billingBatchId);
      },
      error: e => {
        this.uploading = false;
        this.error = e?.error?.message || 'Monthly invoice upload failed.';
      }
    });
  }

  private loadReport(billingBatchId: number) {
    this.http.get<any>(`${API_BASE}/reports/billing/${billingBatchId}`).subscribe({
      next: report => {
        this.report = report;
        this.uploading = false;
      },
      error: e => {
        this.uploading = false;
        this.error = e?.error?.message || 'Invoice imported, but output could not be loaded.';
      }
    });
  }
}
